alias art="php artisan"
alias arti="php artisan tinker"
alias gs="git status"
alias ga="git add ."
alias gcm="git commit -m"
alias gcam="git commit -am"
alias artm="php artisan migrate"
alias cls="clear"
alias artr="php artisan route:list --except-vendor"
alias artra="php artisan route:list"
alias cda="composer dump-autoload -o"
alias p="vendor/bin/pest"
alias pf="vendor/bin/pest --filter"
alias pg="vendor/bin/pest --group="
